checkin/urls.py
from django.conf.urls import url
from django.views import generic
import views


app_name = 'checkin'

urlpatterns = [
    url(r'^$', views.doctor_login),
    url(r'^login/$', views.doctor_login, name="doctor-login"),
    url(r'^oauth2/$', views.auth),
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    url(r'^checkin/$', generic.TemplateView.as_view(template_name="checkin/patient_checkin.html"), name="checkin-view"),
    url(r'^handle_checkin/$', views.handle_checkin, name="handle-checkin"),
    url(r'^patient/update/$', views.update_patient, name="update-patient"),
    url(r'^patient/(?P<patient_id>[0-9]+)/$', views.get_patient, name="get-patient"),
    url(r'^appointment/(?P<appointment_id>[0-9]+)/start/$', views.start_appointment, name="start-appointment"),
]

drchrono/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('checkin.urls')),
]

checkin/models.py
from __future__ import unicode_literals

from django.db import models

class TimeWaiting(models.Model):
    """
    Keeps track of the average time spent waiting by patients
    """
    doctor = models.IntegerField(primary_key=True)
    minutes_waiting = models.IntegerField()
    total_patients = models.IntegerField()

    def average_waiting_time(self):
        return self.minutes_waiting / self.total_patients

checkin/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from oauth2client.client import flow_from_clientsecrets, OAuth2Credentials
from oauth2client.contrib import xsrfutil
from django.conf import settings
from requests import HTTPError

from datetime import date, datetime
from math import floor
import requests

from models import TimeWaiting


FLOW = flow_from_clientsecrets(
    settings.GOOGLE_OAUTH2_CLIENT_SECRETS_JSON,
    scope=["patients:read", "patients:write", "calendar:read", "calendar:write", "clinical:read", "clinical:write"],
    redirect_uri="http://localhost:8000/oauth2"
)


def doctor_login(request):
    """
    Login view for a doctor to setup the check-in kiosk
    :param request:
    :return:
    """
    # TODO: OAUTH credentials are currently stored in a session rather than in the database. Handling needs to be added
    #       for refresh tokens
    access_token = request.session.get('credential')
    credential = OAuth2Credentials.new_from_json(json_data=access_token) if access_token else None

    if credential is None or credential.invalid is True:
        authorize_url = FLOW.step1_get_authorize_url()
        return HttpResponseRedirect(authorize_url)

    else:
        headers = {}
        credential.apply(headers)

        # TODO: implement more robust handling for when an access token expires, currently just deletes the stored
        #       token when a 401 message is encountered
        try:
            response = requests.get('https://drchrono.com/api/users/current', headers=headers)
            response.raise_for_status()

        except HTTPError as err:
            if err.response.status_code == 401:
                del request.session['credential']
                return redirect('checkin:doctor-login')
            else:
                raise

        data = response.json()

        # signed-in doctor's id is stored for use throughout the application
        #   (retrieving and modifying patients and appointments)
        request.session['doctor_id'] = data['id']

        return redirect("checkin:dashboard")


def dashboard(request):
    """
    Dashboard view for a doctor to see which patients have checked in along with the other patients they have later in
    the day. Also shows historic average time patient waiting time.
    :param request:
    :return:
    """
    checked_in_status = "Arrived"

    # TODO: could the credential process be turned into a simple decorator? Credential could then be automatically added
    #   to each function but would require extra documentation since it would not show up in the code
    access_token = request.session.get('credential')
    credential = OAuth2Credentials.new_from_json(json_data=access_token) if access_token else None

    # redirect to oauth2 login flow
    if credential is None:
        return redirect("checkin:doctor-login")

    doctor = request.session['doctor_id']

    appointments = get_todays_unhandled_appointments(credential, doctor)
    enriched_appointments = enrich_appointments(appointments, credential)

    checked_in_patients = []
    upcoming_appointments = []

    for appointment in enriched_appointments:
        if appointment['status'] == checked_in_status:
            checked_in_patients.append(appointment)
        else:
            upcoming_appointments.append(appointment)

    try:
        historic_wait_time = TimeWaiting.objects.get(doctor=doctor)
        historic_average_wait_time = historic_wait_time.average_waiting_time()

    except TimeWaiting.DoesNotExist:
        historic_average_wait_time = 0

    return render(request, "checkin/doctor_dashboard.html", {'doctor': doctor,
                                                             'checked_in_patients': checked_in_patients,
                                                             'upcoming_appointments': upcoming_appointments,
                                                             'historic_average_wait_time': historic_average_wait_time})


def get_todays_unhandled_appointments(credential, doctor):
    """
    Gets todays appointments for a given doctor that have not already been handled (i.e. cancelled, complete, no show,
    in session)
    :param credential: oauth2client credential object
    :param doctor: DrChrono doctor id
    :return:
    """
    handled_appointment_statuses = ["Cancelled", "Complete", "In Session", "No Show"]
    appointments_url = 'https://drchrono.com/api/appointments?doctor={}&date={}'.format(doctor, date.today())

    headers = {}
    credential.apply(headers)

    appointments = []
    while appointments_url:
        response = requests.get(appointments_url, headers=headers)
        response.raise_for_status()
        data = response.json()


        # TODO: should only appointments with a given freshness (i.e. not more than an hour past the appt. time) be returned?
        for appointment in data['results']:
            if appointment['patient'] is not None and not appointment['deleted_flag'] and \
                            appointment['status'] not in handled_appointment_statuses:
                appointments.append(appointment)

        appointments_url = data['next']

    return appointments


def enrich_appointments(appointments, credential):
    """
    Enriches an appointment object with information for the associated patient. Currently only returns the fields
    relevant for building the doctor dashboard.
    :param appointments:
    :param credential:
    :return:
    """
    headers = {}
    credential.apply(headers)

    # enrich appointment information with patient information
    enriched_appointments = []

    for appointment in appointments:
        patients_url = 'https://drchrono.com/api/patients/{}'.format(appointment['patient'])

        response = requests.get(patients_url, headers=headers)
        response.raise_for_status()

        patient = response.json()

        enriched_appointments.append({
            'id': appointment['id'],
            'patient': appointment['patient'],
            'scheduled_time': datetime.strptime(appointment['scheduled_time'], "%Y-%m-%dT%H:%M:%S"),
            'status': appointment['status'],
            # timestamp in ISO 8601 format, i.e. 2014-02-24T15:32:19
            'updated_at': datetime.strptime(appointment['updated_at'], "%Y-%m-%dT%H:%M:%S"),
            'first_name': patient['first_name'],
            'last_name': patient['last_name'],
        })
    return enriched_appointments


def patient_checkin(request):
    """
    Renders the patient sign-in page/form.
    :param request:
    :return:
    """
    return render(request, "checkin/patient_checkin.html")


def handle_checkin(request):
    """
    Checks the users credentials (name and SSN) and then renders some of their demographic information in the
    :param request:
    :return:
    """
    first_name = request.POST['patient-first-name']
    last_name = request.POST['patient-last-name']
    social_security_number = request.POST['patient-social-security-number']

    access_token = request.session.get('credential')
    credential = OAuth2Credentials.new_from_json(json_data=access_token) if access_token else None

    # redirect to oauth2 login flow
    if credential is None:
        return redirect("checkin:doctor-login")

    # the patients endpoint does case-insensitive and partial matching
    patients_url = 'https://drchrono.com/api/patients?first_name={}&last_name={}'.format(first_name, last_name)

    headers = {}
    credential.apply(headers)

    while patients_url:
        response = requests.get(patients_url, headers=headers)
        response.raise_for_status()
        data = response.json()

        for patient in data['results']:
            if patient['first_name'].lower() == first_name.lower() \
                    and patient['last_name'].lower() == last_name.lower() \
                    and patient['social_security_number'] == social_security_number:
                # TODO: should insurance information, custom demographics, or SSN be update-able?
                checked_in_patient = {
                    'id': patient['id'],
                    'first_name': patient['first_name'],
                    'last_name': patient['last_name'],
                    'middle_name': patient['middle_name'],
                    'date_of_birth': patient['date_of_birth'],
                    'gender': patient['gender'],
                    'address': patient['address'],
                    'cell_phone': patient['cell_phone'],
                    'city': patient['city'],
                    'email': patient['email'],
                    'emergency_contact_name': patient['emergency_contact_name'],
                    'emergency_contact_phone': patient['emergency_contact_phone'],
                    'emergency_contact_relation': patient['emergency_contact_relation'],
                    'employer': patient['employer'],
                    'employer_address': patient['employer_address'],
                    'employer_city': patient['employer_city'],
                    'employer_state': patient['employer_state'],
                    'employer_zip_code': patient['employer_zip_code'],
                    'ethnicity': patient['ethnicity'],
                    'home_phone': patient['home_phone'],
                    'preferred_language': patient['preferred_language'],
                    'race': patient['race'],
                    'responsible_party_name': patient['responsible_party_name'],
                    'responsible_party_relation': patient['responsible_party_relation'],
                    'responsible_party_phone': patient['responsible_party_phone'],
                    'responsible_party_email': patient['responsible_party_email'],
                    'state': patient['state'],
                    'zip_code': patient['zip_code'],
                }

checkin/templates/checkin/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}a page has no name{% endblock %}</title>

    <!-- Get Shit Done Kit (front-end styles build on top of bootstrap) http://www.creative-tim.com/product/get-shit-done-kit -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'gsdk.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
</head>
<body>

    <nav class="navbar navbar-ct-azzure" role="navigation">
        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>


            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'checkin:dashboard' %}">Doctor's Dashboard</a></li>
                    <li><a href="{% url 'checkin:checkin-view' %}">Patient Check-in</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

{% block content %}a page has no content{% endblock %}

<script src="{% static 'jquery-1.10.2.js' %}"></script>
<script src="{% static 'jquery-ui-1.10.4.custom.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
<script src="{% static 'gsdk-checkbox.js' %}"></script>
<script src="{% static 'gsdk-radio.js' %}"></script>
<script src="{% static 'gsdk-bootstrapswitch.js' %}"></script>
<script src="{% static 'get-shit-done.js' %}"></script>

</body>
</html>

checkin/templates/checkin/doctor_dashboard.html
{% extends 'checkin/base.html' %}

{% block title %}doctor_dashboard{% endblock %}

{% block content %}

    <div class="container">

        <div class="row">
            <h5 class="pull-right">Historic Average Patient Wait Time: {{historic_average_wait_time}} minutes</h5>
        </div>

        <div class="row">
            <h3 class="text-center">Checked-In Patients</h3>
            <div class="row list-group">
                <div class="row list-header">
                        <p class="list-entry col-md-4">Patient Name</p>
                        <p class="list-entry col-md-4">Time Since Checkin</p>
                        <p class="list-entry col-md-3">Appointment Time</p>
                </div>
                <div class="row">
                    <ul>
                        {% for appointment in checked_in_patients %}
                            <li class="row list-group-item">
                                <p class="list-entry col-md-4">{{appointment.first_name}} {{appointment.last_name}}</p>
                                <p class="list-entry col-md-4">{{appointment.updated_at|timesince}}</p>
                                <p class="list-entry col-md-2">{{appointment.scheduled_time|date:"P"}}</p>
                                <button onclick='location.href="{% url "checkin:start-appointment" appointment.id %}";' class="btn btn-primary col-md-2">See Patient</button>
                            </li><hr/>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>


         <div class="row">
            <h3 class="text-center">Later Appointments</h3>
            <div class="row list-group">
                <div class="row list-header">
                    <p class="list-entry col-md-4">Patient Name</p>
                    <p class="list-entry col-md-4">Appointment Status</p>
                    <p class="list-entry col-md-4">Appointment Time</p>
                </div>
                <div class="row">
                    <ul>
                        {% for appointment in upcoming_appointments %}
                            <li class="row list-group-item">
                                <p class="list-entry col-md-4">{{appointment.first_name}} {{appointment.last_name}}</p>
                                <!-- TODO: is timezone of the doctor taken into account? -->
                                <p class="list-entry col-md-4">{{appointment.status}}</p>
                                <p class="list-entry col-md-4">{{appointment.scheduled_time|date:"P"}}</p>
                            </li><hr/>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

checkin/templates/checkin/patient.html
{% extends 'checkin/base.html' %}

{% block title %}patient_information{% endblock %}

{% block content %}

<div class="container">

        <h3 class="text-center">Patient Information</h3>

        <form action="{% url 'checkin:update-patient' %}" method="post">
            {% csrf_token %}

            <!-- TODO: Disable id input -->
            <div class="hidden form-group">
                <input class="form-control disabled" type="text" id="patient-id" name="patient-id" value="{{patient.id}}">
            </div>

            <div class="form-group">
                <label for="patient-first-name" class=" col-form-label">First Name</label>
                <input class="form-control" type="text" id="patient-first-name" name="patient-first-name" value="{{patient.first_name}}">
            </div>

            <div class="form-group">
                <label for="patient-middle-name" class=" col-form-label">Middle Name</label>
                <input class="form-control" type="text" id="patient-middle-name" name="patient-middle-name" value="{{patient.middle_name}}">
            </div>

            <div class="form-group">
                <label for="patient-last-name" class=" col-form-label">Last Name</label>
                <input class="form-control" type="text" id="patient-last-name" name="patient-last-name" value="{{patient.last_name}}">
            </div>

            <div class="form-group">
                <label for="patient-date-of-birth" class=" col-form-label">Date of Birth</label>
                <input class="form-control" type="date" id="patient-date-of-birth" name="patient-date-of-birth" value="{{patient.date_of_birth}}">
            </div>

            <div class="form-group">
                <label for="patient-gender" class=" col-form-label">Gender</label>
                <select class="form-control" id="patient-gender" name="patient-gender">
                    <option {% if patient.gender == "Male" %} selected="selected" {% endif %}>Male</option>
                    <option {% if patient.gender == "Female" %} selected="selected" {% endif %}>Female</option>
                    <option {% if patient.gender == "Other" %} selected="selected" {% endif %}>Other</option>
                </select>
            </div>

            <div class="form-group">
                <label for="patient-ethnicity" class=" col-form-label">Ethnicity</label>
                <select class="form-control" id="patient-ethnicity" name="patient-ethnicity">
                    <option value="blank" {% if patient.ethnicity == "blank" %} selected="selected" {% endif %}></option>
                    <option value="hispanic" {% if patient.ethnicity == "hispanic" %} selected="selected" {% endif %}>Hispanic</option>
                    <option value="not_hispanic" {% if patient.ethnicity == "not_hispanic" %} selected="selected" {% endif %}>Non-Hispanic</option>
                    <option value="declined" {% if patient.ethnicity == "declined" %} selected="selected" {% endif %}>Declined</option>
                </select>
            </div>

            <div class="form-group">
                <label for="patient-race" class=" col-form-label">Race</label>
                <select class="form-control" id="patient-race" name="patient-race">
                    <option value = "blank" {% if patient.race == "blank" %} selected="selected" {% endif %}></option>
                    <option value = "indian" {% if patient.race == "indian" %} selected="selected" {% endif %}>Indian</option>
                    <option value = "asian" {% if patient.race == "asian" %} selected="selected" {% endif %}>Asian</option>
                    <option value = "black" {% if patient.race == "black" %} selected="selected" {% endif %}>Black</option>
                    <option value = "hawaiin" {% if patient.race == "hawaiian" %} selected="selected" {% endif %}>Hawaiian</option>
                    <option value = "white" {% if patient.race == "white" %} selected="selected" {% endif %}>White</option>
                    <option value = "declined" {% if patient.race == "declined" %} selected="selected" {% endif %}>Declined</option>
                </select>
            </div>

            <div class="form-group">
                <label for="patient-address" class=" col-form-label">Address</label>
                <input class="form-control" type="text" id="patient-address" name="patient-address" value="{{patient.address}}">
            </div>

            <div class="form-group">
                <label for="patient-city" class=" col-form-label">City</label>
                <input class="form-control" type="text" id="patient-city" name="patient-city" value="{{patient.city}}">
            </div>

            <div class="form-group">
                <label for="patient-state" class=" col-form-label">State</label>
                <input class="form-control" type="text" id="patient-state" name="patient-state" value="{{patient.state}}">
            </div>

            <div class="form-group">
                <label for="patient-zip-code" class=" col-form-label">Zip Code (5 digit)</label>
                <input class="form-control" type="text" id="patient-zip-code" name="patient-zip-code" pattern="\d{5}" value="{{patient.zip_code}}">
            </div>

            <div class="form-group">
                <label for="patient-email" class=" col-form-label">Email</label>
                <input class="form-control" type="email" id="patient-email" name="patient-email" value="{{patient.email}}">
            </div>

            <div class="form-group">
                <label for="patient-cell-phone" class=" col-form-label">Cell Phone</label>
                <input class="form-control" type="tel" id="patient-cell-phone" name="patient-cell-phone" value="{{patient.cell_phone}}">
            </div>

            <div class="form-group">
                <label for="patient-home-phone" class=" col-form-label">Home Phone</label>
                <input class="form-control" type="tel" id="patient-home-phone" name="patient-home-phone" value="{{patient.home_phone}}">
            </div>

            <!-- TODO: the following fields are not currently populated -->
            <div class="form-group">
                <label for="patient-preferred-language" class=" col-form-label">Preferred Language</label>
                <input class="form-control" type="text" id="patient-preferred-language" name="patient-preferred-language">
            </div>
            <div class="form-group">
                <label for="patient-emergency-contact-name" class=" col-form-label">Emergency Contact Name</label>
                <input class="form-control" type="text" id="patient-emergency-contact-name" name="patient-emergency-contact-name">
            </div>
            <div class="form-group">
                <label for="patient-emergency-contact-phone" class=" col-form-label">Emergency Contact Phone</label>
                <input class="form-control" type="text" id="patient-emergency-contact-phone" name="patient-emergency-contact-phone">
            </div>
            <div class="form-group">
                <label for="patient-emergency-contact-relation" class=" col-form-label">Emergency Contact Relation</label>
                <input class="form-control" type="text" id="patient-emergency-contact-relation" name="patient-emergency-contact-relation">
            </div>
            <div class="form-group">
                <label for="patient-employer" class=" col-form-label">Employer</label>
                <input class="form-control" type="text" id="patient-employer" name="patient-employer">
            </div>
            <div class="form-group">
                <label for="patient-employer-address" class=" col-form-label">Employer Address</label>
                <input class="form-control" type="text" id="patient-employer-address" name="patient-employer-address">
            </div>
            <div class="form-group">
                <label for="patient-employer-city" class=" col-form-label">Employer City</label>
                <input class="form-control" type="text" id="patient-employer-city" name="patient-employer-city">
            </div>
            <div class="form-group">
                <label for="patient-employer-state" class=" col-form-label">Employer State</label>
                <input class="form-control" type="text" id="patient-employer-state" name="patient-employer-state">
            </div>
            <div class="form-group">
                <label for="patient-employer-zip-code" class=" col-form-label">Employer Zip Code</label>
                <input class="form-control" type="text" id="patient-employer-zip-code" name="patient-employer-zip-code">
            </div>
            <div class="form-group">
                <label for="patient-responsible-party-name" class=" col-form-label">Responsible Party Name</label>
                <input class="form-control" type="text" id="patient-responsible-party-name" name="patient-responsible-party-name">
            </div>
            <div class="form-group">
                <label for="patient-responsible-party-relation" class=" col-form-label">Responsible Party Relation</label>
                <input class="form-control" type="text" id="patient-responsible-party-relation" name="patient-responsible-party-relation">
            </div>
            <div class="form-group">
                <label for="patient-responsible-party-phone" class=" col-form-label">Responsible Party Phone Number</label>
                <input class="form-control" type="text" id="patient-responsible-party-phone" name="patient-responsible-party-phone">
            </div>
            <div class="form-group">
                <label for="patient-responsible-party-email" class=" col-form-label">Responsible Party Email</label>
                <input class="form-control" type="text" id="patient-responsible-party-email" name="patient-responsible-party-email">
            </div>





            <button type="submit" class="btn btn-primary">Confirm Information</button>
        </form>
    </div>

{% endblock content %}

checkin/templates/checkin/patient_checkin.html
{% extends 'checkin/base.html' %}

{% block title %}patient_checkin{% endblock %}

{% block content %}
    <div class="container">

        <h3 class="text-center">Patient Check-In</h3>

        <form action="{% url 'checkin:handle-checkin' %}" method="post">
            {% csrf_token %}

            <div class="form-group">
                <label for="patient-first-name" class=" col-form-label">First Name</label>
                <input class="form-control" type="text" id="patient-first-name" name="patient-first-name">
            </div>

            <div class="form-group">
                <label for="patient-last-name" class=" col-form-label">Last Name</label>
                <input class="form-control" type="text" id="patient-last-name" name="patient-last-name">
            </div>

            <div class="form-group">
                <label for="patient-social-security-number" class=" col-form-label">Social Security Number (xxx-xx-xxxx)</label>
                <input class="form-control" type="password" id="patient-social-security-number" name="patient-social-security-number" pattern="^\d{3}-?\d{2}-?\d{4}$">
            </div>

             <input type="submit" class="btn btn-primary" value="Check-In"/>
        </form>



    </div>

{% endblock content %}